[package]
name = "rust-wasm"
version = "0.1.0"
authors = ["Sergey Isaev <isvforall@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.16.0"
wasmer-runtime = "0.17.0"
wabt = "0.9.2"
